name = "img-host"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"

[[d1_databases]]
binding = "DB"
database_name = "imagehost"
database_id = "e8297db4-525b-4280-9bca-ac87f41861c8"

[vars]
APPLE_CLIENT_ID = "com.imagehost.app"
APPLE_BUNDLE_ID = "com.imagehost.app"
