name = "img-host"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "imghost.isolated.tech", custom_domain = true }
]

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"

[[d1_databases]]
binding = "DB"
database_name = "imghost"
database_id = "904188b3-4cdf-43fc-bd19-c12c616e0d8e"

[vars]
APPLE_CLIENT_ID = "com.imghost.app"
APPLE_BUNDLE_ID = "com.imghost.app"
