name = "img-host"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images"

[[d1_databases]]
binding = "DB"
database_name = "imagehost"
database_id = "preview" # Will be replaced with actual database ID after creation
